substitutions:
  device_name: "slimmelezer"
  device_description: "DIY P1 module to read your smart meter"
  device_password: !secret p1mini_password
  device_api_key: !secret p1mini_api_key
  
esphome:
  name: ${device_name}
  comment: "${device_description}"
  platform: ESP8266
  esp8266_restore_from_flash: true
  board: d1_mini
  name_add_mac_suffix: false
  project:
    name: zuidwijk.slimmelezer
    version: "2.0"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

api:
  encryption:
    key: "${device_api_key}"

ota:
  - platform: esphome
    password: "${device_password}"


logger:
  # Serial logging is disabled by setting the logger baud rate to 0.
  # Otherwise the logger will occupy the hardware UART, making it unavailable
  # for receiving smart meter data on pin D7 (GPIO13).
  baud_rate: 0
  level: INFO        # Set to DEBUG if you are having issues!
  
web_server:
  port: 80

uart:
  baud_rate: 115200
  rx_pin: D7
  rx_buffer_size: 1700
#  debug:   # activate if you are having issues!

external_components:
  - source: github://shelly-rng/esphome-p1mini
    components: [p1_mini]
    refresh: 1s  


p1_mini:
   minimum_period: 0s       # Should be 0 (zero) if the RTS signal is not used.
   buffer_size: 3072        # Needs to be large enough to hold one entire update from the meter.
   data_formats: "BINARY"   # ASCII or BINARY

sensor:
  - platform: p1_mini
    obis_code: "1.7.0"
    name: "Momentary Active Import"
    icon: "mdi:transmission-tower-export"
    unit_of_measurement: W
  - platform: p1_mini
    obis_code: "2.7.0"
    name: "Momentary Active Export"
    icon: "mdi:transmission-tower-import"
    unit_of_measurement: W
  - platform: p1_mini
    obis_code: "1.8.0"
    name: "Cumulative Active Import"
    icon: "mdi:transmission-tower-export"
    unit_of_measurement: kWh
    multiplier: 0.001
    accuracy_decimals: 3
    state_class: "total_increasing"
    device_class: "energy"
  - platform: p1_mini
    obis_code: "2.8.0"
    name: "Cumulative Active Export"
    icon: "mdi:transmission-tower-import"
    unit_of_measurement: kWh
    multiplier: 0.001
    accuracy_decimals: 3
    state_class: "total_increasing"
    device_class: "energy"

  - platform: p1_mini
    obis_code: "32.7.0"
    name: "Voltage Phase 1"
    id: voltage_1
    icon: "mdi:lightning-bolt-outline"
    unit_of_measurement: V
    accuracy_decimals: 1
    on_value: 
      then:
        - component.update: power_1
  - platform: p1_mini
    obis_code: "52.7.0"
    name: "Voltage Phase 2"
    id: voltage_2
    icon: "mdi:lightning-bolt-outline"
    unit_of_measurement: V
    accuracy_decimals: 1
    on_value: 
      then:
        - component.update: power_2
  - platform: p1_mini
    obis_code: "72.7.0"
    name: "Voltage Phase 3"
    id: voltage_3
    icon: "mdi:lightning-bolt-outline"
    unit_of_measurement: V
    accuracy_decimals: 1
    on_value: 
      then:
        - component.update: power_3    

  - platform: p1_mini
    obis_code: "31.7.0"
    name: "Current Phase 1"
    id: current_1
    icon: "mdi:lightning-bolt"
    unit_of_measurement: A
    accuracy_decimals: 1
    on_value: 
      then:
        - component.update: power_1    
  - platform: p1_mini
    obis_code: "51.7.0"
    name: "Current Phase 2"
    id: current_2
    icon: "mdi:lightning-bolt"
    unit_of_measurement: A
    accuracy_decimals: 1
    on_value: 
      then:
        - component.update: power_2    
  - platform: p1_mini
    obis_code: "71.7.0"
    name: "Current Phase 3"
    id: current_3
    icon: "mdi:lightning-bolt"
    unit_of_measurement: A
    accuracy_decimals: 1
    on_value: 
      then:
        - component.update: power_3    

  - platform: p1_mini
    obis_code: "1.8.1"
    name: "Cumulative Active Import T1"
    icon: "mdi:transmission-tower-export"
    unit_of_measurement: kWh
    multiplier: 0.001
    accuracy_decimals: 3
    state_class: "total_increasing"
    device_class: "energy"
  - platform: p1_mini
    obis_code: "2.8.1"
    name: "Cumulative Active Export T1"
    icon: "mdi:transmission-tower-import"
    unit_of_measurement: kWh
    multiplier: 0.001
    accuracy_decimals: 3
    state_class: "total_increasing"
    device_class: "energy"
    
  - platform: p1_mini
    obis_code: "1.8.2"
    name: "Cumulative Active Import T2"
    icon: "mdi:transmission-tower-export"
    unit_of_measurement: kWh
    multiplier: 0.001    
    accuracy_decimals: 3
    state_class: "total_increasing"
    device_class: "energy"
  - platform: p1_mini
    obis_code: "2.8.2"
    name: "Cumulative Active Export T2"
    icon: "mdi:transmission-tower-import"
    unit_of_measurement: kWh
    multiplier: 0.001
    accuracy_decimals: 3
    state_class: "total_increasing"
    device_class: "energy"

  - platform: p1_mini
    obis_code: "0.2.2"
    name: "Tariff code"
    icon: "mdi:transmission-tower-import"

  - platform: template
    name: "Power Phase 1"
    id: power_1
    unit_of_measurement: W
    accuracy_decimals: 0
    state_class: "measurement"
    device_class: "power"
    lambda: |- 
      return (id(voltage_1).state * id(current_1).state * sqrt(2.0));    
  - platform: template
    name: "Power Phase 2"
    id: power_2
    unit_of_measurement: W
    accuracy_decimals: 0
    state_class: "measurement"
    device_class: "power"
    lambda: |- 
      return (id(voltage_2).state * id(current_2).state * sqrt(2.0));    
  - platform: template
    name: "Power Phase 3"
    id: power_3
    unit_of_measurement: W
    accuracy_decimals: 0
    state_class: "measurement"
    device_class: "power"
    lambda: |- 
      return (id(voltage_3).state * id(current_3).state * sqrt(2.0));    
    



  - platform: uptime
    name: "${device_name} Uptime"
  - platform: wifi_signal
    name: "${device_name} Wi-Fi Signal"
    update_interval: 60s
  - platform: adc
    pin: VCC
    name: "${device_name} VCC Voltage"
    update_interval: 5s
    entity_category: diagnostic

text_sensor:
  - platform: p1_mini
    name: "Meter S/N"
    icon: "mdi:identifier"
    identifier: "96.1.0"
  - platform: p1_mini
    name: "Meter GR"
    icon: "mdi:identifier"
    identifier: "96.1.1"
  - platform: p1_mini
    name: "Meter Time"
    identifier: "metertime"
    icon: "mdi:timer-outline"
    device_class: timestamp
    entity_category: diagnostic


  - platform: wifi_info
    ip_address:
      name: "${device_name} IP Address"
    ssid:
      name: "${device_name} Wi-Fi SSID"
    bssid:
      name: "${device_name} Wi-Fi BSSID"
  - platform: version
    name: "${device_name} ESPHome Version"
    hide_timestamp: false
    
binary_sensor:
  - platform: status
    name: "${device_name} Status"